# Generated by Django 5.1.1 on 2025-05-29 07:41

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userRegisteredTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[Users.models.validate_name])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('loginid', models.CharField(max_length=30, unique=True)),
                ('mobile', models.CharField(max_length=10, validators=[Users.models.validate_mobile])),
                ('password', models.CharField(max_length=128, validators=[Users.models.validate_password])),
                ('status', models.CharField(default='waiting', max_length=20)),
            ],
        ),
    ]
